name: Issue Labeled

on:
  issues:
    types: [labeled]

jobs:
  issue-labeled:
    if: github.actor != github.event.issue.user.login
    runs-on: ubuntu-latest
    steps:
      - name: Need reproduce
        if: github.event.label.name == 'ğŸ¤” need reproduce'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œç›®å‰æ‰€æä¾›çš„ä¿¡æ¯æ— æ³•è¿›è¡Œé—®é¢˜çš„å®šä½ä¸æ’æŸ¥ï¼Œè¯·æä¾›å¯ç”¨äºå¤ç°å½“å‰é—®é¢˜çš„å¿…è¦æ“ä½œæ­¥éª¤ï¼Œå¦‚å…³é”®ä»£ç ç‰‡æ®µï¼Œè„±æ•çš„æ•°æ®æ–‡ä»¶ç­‰, 15 å¤©å†…æœªå›å¤issueè‡ªåŠ¨å…³é—­ï¼Œè¯·çŸ¥æ™“ã€‚

            Hello, @${{ github.event.issue.user.login }}, At present, the information provided cannot locate and troubleshoot the problem. Please provide necessary operational steps that can be used to reproduce the current problem, such as key code snippets, desensitized data files, etc. If there is no response within 15 days, the issue will be automatically closed. Please be aware.

      - name: Need more info
        if: github.event.label.name == 'ğŸ‘€ need more info'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä½ æ‰€æä¾›çš„ä¿¡æ¯ä¸è¶³äºæˆ‘ä»¬æ’æŸ¥é—®é¢˜, è¯·å®Œå–„ issue æè¿°, æä¾› gif, æˆªå›¾ç­‰æ–¹å¼, è¯¦ç»†è¯´æ˜å¤ç°æ­¥éª¤, æ„Ÿè°¢é…åˆ, è°¢è°¢!

            Hello, @${{ github.event.issue.user.login }}, the information you provided is not enough for us to troubleshoot the problem. Please complete the issue description, provide gifs, screenshots, etc. And explain the reproduction steps in detail. Thanks so much for your cooperation!
      
      - name: ExcuseMe
        if: github.event.label.name == 'ğŸ¤·â€â™‚ï¸ ExcuseMe'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œä¸ºäº†æ›´åŠ å¿«é€Ÿé«˜æ•ˆçš„è§£å†³é—®é¢˜ï¼Œè¯·ç”¨æ›´åŠ æ¸…æ™°çš„è¯­è¨€æè¿°å½“å‰é—®é¢˜ï¼Œæ–¹ä¾¿ç›¸å…³åŒå­¦çš„å¤„ç†ï¼Œè°¢è°¢!

            Hello, @${{ github.event.issue.user.login }}, In order to solve the problem more quickly and efficiently, please describe the current problem in clearer language for the convenience of relevant students. Thank you!

      - name: Working
        if: github.event.label.name == 'ğŸ’» working'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œç›®å‰æ­£åœ¨è¿›è¡Œé—®é¢˜çš„ç¡®è®¤ä¸å¤ç°ï¼Œæœ‰ç»“è®ºä¼šåŠæ—¶åé¦ˆ, æ„Ÿè°¢!

            Hello, @${{ github.event.issue.user.login }}, We are currently confirming and reproducing the issue, and will provide timely feedback if there is a conclusion. Thank you.

      - name: Invalid
        if: github.event.label.name == 'â›” invalid'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment,close-issue'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯·æŒ‰ç…§ issue æ¨¡æ¿å¡«å†™ç›¸å…³ä¿¡æ¯, æ–¹ä¾¿å¤§å®¶é«˜æ•ˆæ²Ÿé€šã€‚

            Hello @${{ github.event.issue.user.login }}, please fill in the relevant information according to the issue template to facilitate communication efficiently. Thanks so much!

      - name: Enhancement
        if: github.event.label.name == 'âš¡ enhancement'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæ„Ÿè°¢ä½ çš„å»ºè®®, æˆ‘ä»¬ä¼šåŠæ—¶è¯„ä¼°å’Œæ’æœŸ, è°¢è°¢!

            Hello, @${{ github.event.issue.user.login }}, thanks for your advice. We will evaluate and schedule in time. Thank you!

      - name: Bug
        if: github.event.label.name == 'ğŸ› bug'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œå¾ˆæŠ±æ­‰ç»™ä½ å¸¦æ¥äº†ä¸å¥½çš„ä½“éªŒ, æˆ‘ä»¬ä¼šå°½å¿«æ’æŸ¥é—®é¢˜å¹¶ä¿®å¤, è¯·å…³æ³¨åç»­å‘å¸ƒæ—¥å¿—.

            Hello, @${{ github.event.issue.user.login }}, We are so sorry for the bad experience. We will troubleshoot and fix the problem as soon as possible. Please pay attention to the follow-up change logs.

      - name: Need test cases or docs
        if: github.event.label.name == 'ğŸ™ need test cases or docs'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œå¾ˆæŠ±æ­‰ç»™ä½ å¸¦æ¥äº†ä¸å¥½çš„ä½“éªŒï¼Œç›®å‰è¿˜åœ¨ç¡®è®¤é—®é¢˜åŸå› ï¼Œæˆ‘ä»¬ä¼šåŠæ—¶è¿›è¡Œé—®é¢˜çš„åé¦ˆï¼Œè°¢è°¢ï¼

            Hello, @${{ github.event.issue.user.login }}, I'm sorry for the bad experience you had. We are still confirming the cause of the problem and will provide timely feedback. Thank you ï¼

      - name: Accepted
        if: github.event.label.name == 'âœ… accepted'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œç»è¿‡æˆ‘ä»¬çš„åå¤è®¨è®º, ä½ çš„éœ€æ±‚ç°å·²è¢«é‡‡çº³, æˆ‘ä»¬ä¼šæ’æœŸå¼€å‘, è¯·å…³æ³¨åç»­å‘å¸ƒæ—¥å¿—.

            Hello, @${{ github.event.issue.user.login }}, your feature request have been accepted After our repeated discussion. We will schedule the development, please pay attention to the follow-up release logs

      - name: Loading
        if: github.event.label.name == 'â˜•Loading'
        uses: actions-cool/issues-helper@main
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œè¯¥åŠŸèƒ½ç›®å‰å·²åœ¨åŠŸèƒ½çš„è¿­ä»£è®¡åˆ’å½“ä¸­ï¼Œè¿‘æœŸä¼šå¯¹å¤–é€å‡º, è¯·å…³æ³¨åç»­å‘å¸ƒæ—¥å¿—.

            Hello, @${{ github.event.issue.user.login }}, This feature is currently in the iteration plan and will be released to the public soon. Please pay attention to the subsequent release logs.

      - name: help wanted
        if: github.event.label.name == 'ğŸ¤© help wanted'
        uses: actions-cool/issues-helper@v1.2
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello @${{ github.event.issue.user.login }}. We totally like your proposal/feedback, welcome PRã€‚
            ä½ å¥½ @${{ github.event.issue.user.login }}ï¼Œæˆ‘ä»¬å®Œå…¨åŒæ„ä½ çš„æè®®/åé¦ˆï¼Œæ¬¢è¿PRã€‚
